### PR TITLE
Update api.py

### LINKED ISSUE #5: Błąd  "list indices must be integers or slices, not str"
Dzień dobry. Pisałem do Pana na telefonie w sprawie błędu który się pojawia w integracji SmartThings-Soundbar.
Poniżej wklejam to co pojawia się w Home Assistant:
```
Logger: homeassistant.helpers.entity
Source: custom_components/smartthings_soundbar/api.py:60
First occurred: 10:36:59 (344 occurrences)
Last logged: 11:34:10

Update for media_player.samsung_q70r fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 76, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 60, in device_update
    self._source_list = device_all_sources["value"]
TypeError: list indices must be integers or slices, not str 
```

### PR DESCRIPTION
**Pull request by Zolli**
Removed unnecessary accessor when populating device sources Fixes #5

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
This fix will probably break compatibility with older devices

**Comment by Zolli** [comment]
Okay, i check it, but i not see anythig else in the first place, because this component worked for me at least a month. and the error mentioned in the issue ticket is just started a week ago. Maybe the api response changed for specific devices?

**Comment by PiotrMachowski** [comment]
Yes, it seems like it has been changed for new devices - I use HW-Q80R and it works correctly.

**Comment by Zolli** [comment]
Woah, thats wierd :D I use a Q90R and the issue author is using a Q70R, its all from the same series.

**Comment by PiotrMachowski** [comment]
Ok, I have checked it and I have a pending update - it will probably break integration for me

**Comment by PiotrMachowski** [comment]
Can you run [this script](https://pastebin.com/H3tZxJMq) and send me results here or at _piotr.machowski.dev [at] gmail [dot] com_?

**Comment by PiotrMachowski** [comment]
Issue should be fixed now

**Pull request closed without merging**
